spring:
  datasource:
    url: jdbc:mysql://localhost:3307/library_database
    username: root
    password: 1993

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
